#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/ali/.Xmodmap"
xrdb "/home/ali/.Xresources"
xset -b

eval `ssh-agent -s`

xrandr --output DP2 --mode 3840x2160
xrandr --output HDMI2 --left-of DP2 --auto

setenv wpsetters feh
fbsetbg -a ~/.fluxbox/bluebsd.jpg

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/ali/.fluxbox/log"
